const AllQuestions = [
  {
    id: 1,
    sortNumber: 1,
    type: "choosing",
    text: "أختر الإجابة الصحيحة",
    isEditModeActive: false,
    questions: [
      {
        id: 1,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "هي دين إبراهيم عليه السلام وكان عليها النبي صلى الله عليه وسلم قبل البعثة:",
        options: [
          { id: 1, text: "المجوسية", isCorrect: false },
          { id: 2, text: "النصرانية", isCorrect: false },
          { id: 3, text: "اليهودية", isCorrect: false },
          { id: 4, text: "الحنفية", isCorrect: true },
        ],
      },
      {
        id: 2,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "أول مسجد بني في الإسلام هو:",
        options: [
          { id: 1, text: "المسجد النبوي", isCorrect: false },
          { id: 2, text: "المسجد الأقصى", isCorrect: false },
          { id: 3, text: "مسجد قباء", isCorrect: true },
          { id: 4, text: "المسجد الحرام", isCorrect: false },
        ],
      },
      {
        id: 3,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "عدد ركعات صلاة الفجر هو:",
        options: [
          { id: 1, text: "أربع ركعات", isCorrect: false },
          { id: 2, text: "ركعتان", isCorrect: true },
          { id: 3, text: "ثلاث ركعات", isCorrect: false },
          { id: 4, text: "خمس ركعات", isCorrect: false },
        ],
      },
      {
        id: 4,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "المدينة التي هاجر إليها النبي صلى الله عليه وسلم هي:",
        options: [
          { id: 1, text: "الطائف", isCorrect: false },
          { id: 2, text: "المدينة المنورة", isCorrect: true },
          { id: 3, text: "مكة المكرمة", isCorrect: false },
          { id: 4, text: "بدر", isCorrect: false },
        ],
      },
      {
        id: 5,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "أطول سورة في القرآن الكريم هي:",
        options: [
          { id: 1, text: "سورة البقرة", isCorrect: true },
          { id: 2, text: "سورة آل عمران", isCorrect: false },
          { id: 3, text: "سورة النساء", isCorrect: false },
          { id: 4, text: "سورة الأعراف", isCorrect: false },
        ],
      },
      {
        id: 6,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "ليلة الإسراء والمعراج كانت من مكة إلى:",
        options: [
          { id: 1, text: "المدينة", isCorrect: false },
          { id: 2, text: "بدر", isCorrect: false },
          { id: 3, text: "القدس", isCorrect: true },
          { id: 4, text: "خيبر", isCorrect: false },
        ],
      },
      {
        id: 7,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "عدد أركان الإسلام هو:",
        options: [
          { id: 1, text: "ثلاثة", isCorrect: false },
          { id: 2, text: "خمسة", isCorrect: true },
          { id: 3, text: "سبعة", isCorrect: false },
          { id: 4, text: "أربعة", isCorrect: false },
        ],
      },
      {
        id: 8,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "الصحابي الذي نام في فراش النبي ليلة الهجرة هو:",
        options: [
          { id: 1, text: "أبو بكر الصديق", isCorrect: false },
          { id: 2, text: "علي بن أبي طالب", isCorrect: true },
          { id: 3, text: "عمر بن الخطاب", isCorrect: false },
          { id: 4, text: "عثمان بن عفان", isCorrect: false },
        ],
      },
      {
        id: 9,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "السورة التي تسمى قلب القرآن هي:",
        options: [
          { id: 1, text: "سورة الرحمن", isCorrect: false },
          { id: 2, text: "سورة يس", isCorrect: true },
          { id: 3, text: "سورة الملك", isCorrect: false },
          { id: 4, text: "سورة الفاتحة", isCorrect: false },
        ],
      },
      {
        id: 10,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "أول من أسلم من الصبيان هو:",
        options: [
          { id: 1, text: "عبدالله بن عباس", isCorrect: false },
          { id: 2, text: "علي بن أبي طالب", isCorrect: true },
          { id: 3, text: "زيد بن حارثة", isCorrect: false },
          { id: 4, text: "أنس بن مالك", isCorrect: false },
        ],
      },
      {
        id: 11,
        type: "image",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "ما هى خريطة سوريا الصحيحة؟",
        options: [
          { id: 1, src: "./src/images/answers/a1-image.png", isCorrect: false },
          { id: 2, src: "./src/images/answers/a2-image.png", isCorrect: true },
          { id: 3, src: "./src/images/answers/a3-image.png", isCorrect: false },
          { id: 4, src: "./src/images/answers/a4-image.png", isCorrect: false },
        ],
      },
    ],
  },
  {
    id: 2,
    sortNumber: 2,
    type: "paragraph",
    isEditModeActive: false,
    text: "إقرأ القطعة وأجب عما يأتي:",
    subText:
      "كنت منذ صغري، أحبّ البيئة ومخلوقاتها، وأعجب برؤية أغصان الشجر في البساتين والأعشاب في الحقول، ومع تقدمي في العمر، استمر حبي للطبيعة، ولكن حتى الكائنات أصابها بعض التبدل والتغير، إذ مارست صيد العصافير، غير مدرك الفارق العظيم بين حب البيئة، وقتل هذه الطيور الملونة في يوم كنت أمارس فيه هواية الصيد لمحت بساطة جميلة الألوان، وهي على غصن في شجرة سنديان تنقي، غافلة عما يحيط بها من خطر لقد قمت صوبتها بطلقة واحدة من بندقيتي، سقطت بعدها على العشب الذي يغمره الدفء، فاقتربت منها لأشاهدها، وهي تلفظ أنفاسها؛ ثبت على ما فعلت فبكيت واقفًا كأنني جذع شجرة. وقد تكون عيناهما الدامعتان هما اللتان جعلتاني ثابتًا في مكاني أنظر إليها وهي في آخر لحظاتها رجعت وأنا أبكي، وأقول لنفسي: لماذا فعلت هذا؟! منذ ذلك الحين، أقلعت عن الصيد، وعدت إلى عاداتي القديمة في . حب البيئة والاستمتاع بجمالها. ",
    editQuestionMode: false,
    showQuestionsActions: false,
    questions: [
      {
        id: 1,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "هي دين إبراهيم عليه السلام وكان عليها النبي صلى الله عليه وسلم قبل البعثة:",
        options: [
          { id: 1, text: "المجوسية", isCorrect: false },
          { id: 2, text: "النصرانية", isCorrect: false },
          { id: 3, text: "اليهودية", isCorrect: false },
          { id: 4, text: "الحنفية", isCorrect: true },
        ],
      },
      {
        id: 2,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "أول مسجد بني في الإسلام هو:",
        options: [
          { id: 1, text: "المسجد النبوي", isCorrect: false },
          { id: 2, text: "المسجد الأقصى", isCorrect: false },
          { id: 3, text: "مسجد قباء", isCorrect: true },
          { id: 4, text: "المسجد الحرام", isCorrect: false },
        ],
      },
      {
        id: 3,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "عدد ركعات صلاة الفجر هو:",
        options: [
          { id: 1, text: "أربع ركعات", isCorrect: false },
          { id: 2, text: "ركعتان", isCorrect: true },
          { id: 3, text: "ثلاث ركعات", isCorrect: false },
          { id: 4, text: "خمس ركعات", isCorrect: false },
        ],
      },
      {
        id: 4,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "المدينة التي هاجر إليها النبي صلى الله عليه وسلم هي:",
        options: [
          { id: 1, text: "الطائف", isCorrect: false },
          { id: 2, text: "المدينة المنورة", isCorrect: true },
          { id: 3, text: "مكة المكرمة", isCorrect: false },
          { id: 4, text: "بدر", isCorrect: false },
        ],
      },
      {
        id: 5,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "أطول سورة في القرآن الكريم هي:",
        options: [
          { id: 1, text: "سورة البقرة", isCorrect: true },
          { id: 2, text: "سورة آل عمران", isCorrect: false },
          { id: 3, text: "سورة النساء", isCorrect: false },
          { id: 4, text: "سورة الأعراف", isCorrect: false },
        ],
      },
      {
        id: 6,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "ليلة الإسراء والمعراج كانت من مكة إلى:",
        options: [
          { id: 1, text: "المدينة", isCorrect: false },
          { id: 2, text: "بدر", isCorrect: false },
          { id: 3, text: "القدس", isCorrect: true },
          { id: 4, text: "خيبر", isCorrect: false },
        ],
      },
      {
        id: 7,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "عدد أركان الإسلام هو:",
        options: [
          { id: 1, text: "ثلاثة", isCorrect: false },
          { id: 2, text: "خمسة", isCorrect: true },
          { id: 3, text: "سبعة", isCorrect: false },
          { id: 4, text: "أربعة", isCorrect: false },
        ],
      },
      {
        id: 8,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "الصحابي الذي نام في فراش النبي ليلة الهجرة هو:",
        options: [
          { id: 1, text: "أبو بكر الصديق", isCorrect: false },
          { id: 2, text: "علي بن أبي طالب", isCorrect: true },
          { id: 3, text: "عمر بن الخطاب", isCorrect: false },
          { id: 4, text: "عثمان بن عفان", isCorrect: false },
        ],
      },
      {
        id: 9,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "السورة التي تسمى قلب القرآن هي:",
        options: [
          { id: 1, text: "سورة الرحمن", isCorrect: false },
          { id: 2, text: "سورة يس", isCorrect: true },
          { id: 3, text: "سورة الملك", isCorrect: false },
          { id: 4, text: "سورة الفاتحة", isCorrect: false },
        ],
      },
      {
        id: 10,
        type: "text",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "أول من أسلم من الصبيان هو:",
        options: [
          { id: 1, text: "عبدالله بن عباس", isCorrect: false },
          { id: 2, text: "علي بن أبي طالب", isCorrect: true },
          { id: 3, text: "زيد بن حارثة", isCorrect: false },
          { id: 4, text: "أنس بن مالك", isCorrect: false },
        ],
      },
      {
        id: 11,
        type: "image",
        editQuestionMode: false,
        showQuestionsActions: false,
        text: "ما هى خريطة سوريا الصحيحة؟",
        options: [
          { id: 1, src: "./src/images/answers/a1-image.png", isCorrect: false },
          { id: 2, src: "./src/images/answers/a2-image.png", isCorrect: true },
          { id: 3, src: "./src/images/answers/a3-image.png", isCorrect: false },
          { id: 4, src: "./src/images/answers/a4-image.png", isCorrect: false },
        ],
      },
    ],
  },
];

export default AllQuestions;
